/* Original recorded loop, procedural chip Foley, and one shared volume panel. */
(function(){
'use strict';
let context=null,musicGain=null,effectsGain=null,masterGain=null,analyser=null,source=null,active=true,muted=false,talking=false,speech=null,meterFrame=0,lastChip=-1,voices=[],sounds=0;
const settings={master:75,music:38,effects:75,dealer:90};try{const saved=JSON.parse(localStorage.getItem('holdem-audio')||'{}');for(const k of Object.keys(settings))if(Number.isFinite(saved[k]))settings[k]=Math.max(0,Math.min(100,saved[k]));muted=!!saved.muted}catch(e){}
const music=new Audio('audio/holdem-velvet-soul.wav');music.loop=true;music.preload='none';music.playsInline=true;
const toggle=document.createElement('button');toggle.className='he-audio-toggle';toggle.type='button';toggle.textContent='♫ Audio';toggle.setAttribute('aria-expanded','false');
const panel=document.createElement('section');panel.className='he-audio-panel';panel.hidden=true;panel.setAttribute('aria-label','Hold Em audio settings');
panel.innerHTML='<header><div><small>VELVET SOUL</small><h2>Sound & music</h2></div><button data-close aria-label="Close audio settings">×</button></header><p>Original mellow R&B · warm keys and soft drums. Dealer: Southern Gentleman, a slow, low, polished voice with dry wit.</p>'+Object.entries({master:'Master volume',music:'Background music',effects:'Chips & effects',dealer:'Dealer voice'}).map(([key,name])=>'<label><span>'+name+'</span><output data-value="'+key+'">'+settings[key]+'%</output><input type="range" data-volume="'+key+'" aria-label="'+name+'" min="0" max="100" value="'+settings[key]+'"></label>').join('')+'<div class="he-audio-meter" role="meter" aria-label="Sound output" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><i></i></div><div class="he-audio-buttons"><button data-mute></button><button data-preview>Preview chips</button></div><small data-audio-status>Sound starts after your first click or tap.</small>';
document.body.append(toggle,panel);
function save(){try{localStorage.setItem('holdem-audio',JSON.stringify({...settings,muted}))}catch(e){}apply();window.dispatchEvent(new Event('holdem:audio-settings'))}
function apply(){if(context){const at=context.currentTime;masterGain.gain.setTargetAtTime(muted?0:settings.master/100,at,.035);musicGain.gain.setTargetAtTime(settings.music/100*(talking?.38:1),at,.12);effectsGain.gain.setTargetAtTime(settings.effects/100,at,.035)}panel.querySelector('[data-mute]').textContent=muted?'Unmute all':'Mute all';toggle.classList.toggle('muted',muted);if((muted||!settings.master||!settings.dealer)&&speech)stopVoice()}
async function unlock(){if(!active||document.hidden)return;try{if(!context){context=new(window.AudioContext||window.webkitAudioContext)();masterGain=context.createGain();musicGain=context.createGain();effectsGain=context.createGain();const limiter=context.createDynamicsCompressor();limiter.threshold.value=-10;limiter.knee.value=18;limiter.ratio.value=3;limiter.attack.value=.008;limiter.release.value=.12;analyser=context.createAnalyser();analyser.fftSize=256;source=context.createMediaElementSource(music);source.connect(musicGain);musicGain.connect(masterGain);effectsGain.connect(masterGain);masterGain.connect(limiter);limiter.connect(analyser);analyser.connect(context.destination);apply()}await context.resume();if(music.paused&&!muted&&settings.music)await music.play();panel.querySelector('[data-audio-status]').textContent='Original score · no third-party music samples.'}catch(e){panel.querySelector('[data-audio-status]').textContent='Tap Audio to enable sound on this device.'}}
function noise(){const b=context.createBuffer(1,Math.ceil(context.sampleRate*.18),context.sampleRate),data=b.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.exp(-i/(context.sampleRate*.035));return b}
let noiseBuffer=null;
function chip(kind='land',strength=1){if(!context||context.state!=='running'||muted||document.hidden||!active||sounds>16)return;const now=context.currentTime;if(now-lastChip<.024)return;lastChip=now;sounds++;const g=context.createGain(),filter=context.createBiquadFilter(),n=context.createBufferSource();if(!noiseBuffer)noiseBuffer=noise();n.buffer=noiseBuffer;filter.type='bandpass';filter.frequency.value=kind==='slide'?1600:2900+Math.random()*900;filter.Q.value=.65;g.gain.setValueAtTime((kind==='slide'?.055:.10)*strength,now);g.gain.exponentialRampToValueAtTime(.0001,now+.11);n.connect(filter);filter.connect(g);g.connect(effectsGain);n.start(now);n.stop(now+.13);if(kind!=='slide')for(const f of[1700+Math.random()*450,3100+Math.random()*650]){const o=context.createOscillator(),a=context.createGain();o.type='sine';o.frequency.setValueAtTime(f,now);o.frequency.exponentialRampToValueAtTime(f*.83,now+.075);a.gain.setValueAtTime(.027*strength,now);a.gain.exponentialRampToValueAtTime(.0001,now+.065);o.connect(a);a.connect(effectsGain);o.start(now);o.stop(now+.09);o.onended=()=>{a.disconnect();o.disconnect()}}n.onended=()=>{sounds--;n.disconnect();filter.disconnect();g.disconnect()}}
function scream(){if(!context||context.state!=='running'||muted||document.hidden||!active)return;const now=context.currentTime,g=context.createGain();g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(.20,now+.09);g.gain.exponentialRampToValueAtTime(.001,now+1.15);g.connect(effectsGain);for(const [frequency,level]of[[520,.6],[1040,.20],[1560,.13]]){const voice=context.createOscillator(),a=context.createGain(),filter=context.createBiquadFilter();voice.type='sawtooth';voice.frequency.setValueAtTime(frequency,now);voice.frequency.exponentialRampToValueAtTime(frequency*.46,now+1.1);filter.type='bandpass';filter.frequency.value=frequency===520?800:frequency===1040?1300:2700;filter.Q.value=2.4;a.gain.value=level;voice.connect(filter);filter.connect(a);a.connect(g);voice.start(now);voice.stop(now+1.2);voice.onended=()=>{voice.disconnect();filter.disconnect();a.disconnect()}}setTimeout(()=>g.disconnect(),1400)}
function voiceList(){voices=window.speechSynthesis?.getVoices()||[]}voiceList();window.speechSynthesis?.addEventListener('voiceschanged',voiceList);
function speak(text){if(!active||document.hidden||muted||!settings.master||!settings.dealer)return false;stopVoice();if(!window.speechSynthesis)return false;const line=new SpeechSynthesisUtterance(text);const english=voices.filter(v=>/^en/i.test(v.lang));line.voice=english.find(v=>/Guy.*Natural/i.test(v.name)&&/^en-US/i.test(v.lang))||english.find(v=>/Guy|David|Christopher|Roger/i.test(v.name)&&/^en-US/i.test(v.lang))||english.find(v=>/Daniel|George|Ryan/i.test(v.name))||english.find(v=>v.localService)||english[0]||null;line.pitch=.84+Math.random()*.035;line.rate=.88+Math.random()*.035;line.volume=settings.master/100*settings.dealer/100;const finish=()=>{if(speech===line){speech=null;talking=false;apply();window.dispatchEvent(new Event('holdem:voice-end'))}};line.onstart=()=>{speech=line;talking=true;apply();window.dispatchEvent(new Event('holdem:voice-start'))};line.onend=finish;line.onerror=finish;speech=line;window.speechSynthesis.speak(line);return true}
function stopVoice(){window.speechSynthesis?.cancel();speech=null;talking=false;apply()}
function mute(value){muted=typeof value==='boolean'?value:!muted;save();if(!muted)unlock();return muted}
const meterData=new Uint8Array(256);function meter(){meterFrame=0;if(panel.hidden)return;let value=0;if(analyser){analyser.getByteTimeDomainData(meterData);for(const v of meterData)value+=(v-128)*(v-128);value=Math.min(100,Math.sqrt(value/256)/40*100)}const bar=panel.querySelector('.he-audio-meter');bar.querySelector('i').style.width=value+'%';bar.setAttribute('aria-valuenow',String(Math.round(value)));meterFrame=requestAnimationFrame(meter)}
function close(){panel.hidden=true;toggle.setAttribute('aria-expanded','false');cancelAnimationFrame(meterFrame);meterFrame=0}
toggle.onclick=()=>{panel.hidden=!panel.hidden;toggle.setAttribute('aria-expanded',String(!panel.hidden));unlock();if(!panel.hidden)meter();else close()};panel.querySelector('[data-close]').onclick=close;panel.querySelector('[data-mute]').onclick=()=>mute();panel.querySelector('[data-preview]').onclick=async()=>{await unlock();chip('land',1.2);setTimeout(()=>chip('land',.8),100)};
for(const input of panel.querySelectorAll('[data-volume]'))input.oninput=()=>{settings[input.dataset.volume]=Number(input.value);panel.querySelector('[data-value="'+input.dataset.volume+'"]').textContent=input.value+'%';save();unlock()};
document.addEventListener('pointerdown',unlock,{passive:true});document.addEventListener('keydown',e=>{if(e.code==='Escape')close()});document.addEventListener('visibilitychange',()=>{if(document.hidden){music.pause();stopVoice()}else if(active&&context)unlock()});
window.addEventListener('holdem:chip-sound',e=>chip(e.detail?.kind,e.detail?.strength||1));window.addEventListener('message',e=>{if(e.source===parent&&e.data?.type==='game-room:stop-audio'){active=false;music.pause();stopVoice();context?.suspend()}});window.addEventListener('pagehide',()=>{active=false;music.pause();stopVoice();context?.close().catch(()=>{})});
apply();window.HoldEmAudio={unlock,chip,scream,speak,stopVoice,mute,get muted(){return muted},get talking(){return talking},get volume(){return settings.master/100*settings.dealer/100}};
})();
