/* Showdown equity from your cards and the public board. Never reads rival cards. */
(function(){
'use strict';
function simulation(job){
 let seed=job.seed>>>0,score=0,done=0;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296},known=new Set([...job.hole,...job.board]),unknown=Array.from({length:52},(_,i)=>i).filter(i=>!known.has(i));
 function compare(a,b){for(let i=0;i<a.length;i++){const d=a[i]-(b[i]||0);if(d)return Math.sign(d)}return 0}
 function five(cards){const ranks=cards.map(c=>2+c%13).sort((a,b)=>b-a),counts={};for(const r of ranks)counts[r]=(counts[r]||0)+1;const groups=Object.entries(counts).map(([r,n])=>[Number(r),n]).sort((a,b)=>b[1]-a[1]||b[0]-a[0]),unique=[...new Set(ranks)],flush=cards.every(c=>Math.floor(c/13)===Math.floor(cards[0]/13)),straight=unique.length===5?(unique[0]-unique[4]===4?unique[0]:unique.join(',')==='14,5,4,3,2'?5:0):0;
  if(flush&&straight)return[8,straight];if(groups[0][1]===4)return[7,groups[0][0],groups[1][0]];if(groups[0][1]===3&&groups[1][1]===2)return[6,groups[0][0],groups[1][0]];if(flush)return[5,...ranks];if(straight)return[4,straight];if(groups[0][1]===3)return[3,groups[0][0],...groups.slice(1).map(g=>g[0])];if(groups[0][1]===2&&groups[1][1]===2)return[2,Math.max(groups[0][0],groups[1][0]),Math.min(groups[0][0],groups[1][0]),groups[2][0]];if(groups[0][1]===2)return[1,groups[0][0],...groups.slice(1).map(g=>g[0])];return[0,...ranks];
 }
 function rank(cards){let best=null;for(let a=0;a<3;a++)for(let b=a+1;b<4;b++)for(let c=b+1;c<5;c++)for(let d=c+1;d<6;d++)for(let e=d+1;e<7;e++){const r=five([cards[a],cards[b],cards[c],cards[d],cards[e]]);if(!best||compare(r,best)>0)best=r}return best}
 return {run(count){for(let n=0;n<count&&done<job.trials;n++,done++){const deck=unknown.slice();for(let i=deck.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}const board=job.board.slice();while(board.length<5)board.push(deck.pop());const own=rank([...job.hole,...board]);let ties=1,lost=false;for(let rival=0;rival<job.opponents;rival++){const result=compare(rank([deck.pop(),deck.pop(),...board]),own);if(result>0){lost=true;break}if(result===0)ties++}if(!lost)score+=1/ties}return done>=job.trials},value(){return score/Math.max(1,done)*100}};
}
let worker=null,activeKey='',fallback=null,sequence=0,lastState=null;const widget=document.createElement('aside');widget.className='hand-equity';widget.hidden=true;widget.setAttribute('aria-label','Estimated showdown win chance');widget.innerHTML='<span>EST. WIN CHANCE</span><strong>—</strong><small>Against active opponents</small>';document.body.appendChild(widget);
try{const source='const simulation='+simulation.toString()+';onmessage=e=>{const calc=simulation(e.data);calc.run(e.data.trials);postMessage({key:e.data.key,value:calc.value()})};',url=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);worker.onmessage=e=>finish(e.data);worker.onerror=()=>{worker?.terminate();worker=null;activeKey='';if(lastState)update(lastState)}}catch(e){}
function finish({key,value}){if(key!==activeKey)return;widget.querySelector('strong').textContent='≈ '+value.toFixed(1)+'%';widget.querySelector('small').textContent='Showdown equity · estimate'}
function update(s){lastState=s;if(s.gameType==='blackjack'){activeKey='';sequence++;clearTimeout(fallback);widget.dataset.ready='false';widget.hidden=true;return}const self=window.TablePoker.self,own=s.players[self],opponents=s.players.filter(p=>p.inHand&&!p.folded&&p.id!==self).length;if(own.hole.length!==2||s.phase==='idle'){widget.dataset.ready='false';return}widget.dataset.ready='true';const key=JSON.stringify([s.session,s.hand,own.hole.map(c=>c.id),s.board.map(c=>c.id),opponents,own.folded]);if(key===activeKey)return;activeKey=key;clearTimeout(fallback);sequence++;
 if(own.folded){widget.querySelector('strong').textContent='Folded';widget.querySelector('small').textContent='Waiting for the next hand';return}if(!opponents){finish({key,value:100});return}
 let seed=2166136261;for(const c of key)seed=Math.imul(seed^c.charCodeAt(0),16777619);const job={key,seed,hole:own.hole.map(c=>c.id),board:s.board.map(c=>c.id),opponents,trials:1000};widget.querySelector('strong').textContent='…';widget.querySelector('small').textContent='Reading the board';
 if(worker){worker.postMessage(job);return}const calc=simulation(job),token=sequence;function chunk(){if(token!==sequence)return;if(calc.run(8))finish({key,value:calc.value()});else fallback=setTimeout(chunk,12)}chunk();
}
window.addEventListener('holdem:state',e=>update(e.detail));window.addEventListener('pagehide',()=>{worker?.terminate();clearTimeout(fallback)});
window.HoldEmEquity={element:widget,update};
})();
