/* Mode first, then character selection. */
(function(){
'use strict';
window.HoldEmMainMenu=function({onPlay=()=>{},onReplay=()=>{},getConfig=()=>({chosen:2,customizations:{}})}={}){
 const root=document.createElement('section');root.className='he-main-menu';root.setAttribute('aria-label','Cards main menu');
 root.innerHTML=`<header class="he-main-header"><span class="he-main-brand"><i aria-hidden="true">♠</i> THE GAME ROOM</span><button type="button" data-exit>← Game Room</button></header>
 <div class="he-main-content"><p class="he-main-eyebrow">THE TABLE IS YOURS</p><h1>Cards<span class="he-main-dot">.</span></h1><p class="he-main-description">Same familiar faces. Two ways to play.<br>Choose your game, then take your seat.</p>
 <div class="cards-game-picker" role="group" aria-label="Choose card game"><button type="button" data-game="holdem" aria-pressed="true"><b>Hold Em</b><small>Read the table. Win the pot.</small></button><button type="button" data-game="blackjack" aria-pressed="false"><b>Blackjack</b><small>Beat the house. Reach 21.</small></button></div><div class="he-mode-buttons"><button class="he-main-play" type="button" data-single>Single Player <span>↗</span></button><button class="he-main-play he-secondary" type="button" data-online>Multiplayer <span>↗</span></button></div>
 <section class="he-mode-panel" data-single-panel hidden><label>BOT DIFFICULTY</label><div class="he-difficulty" role="group" aria-label="Bot difficulty"><button data-level="easy">Easy</button><button data-level="medium" aria-pressed="true">Medium</button><button data-level="hard">Hard</button></div><p data-level-copy>Balanced play, with occasional bluffs.</p><button class="he-main-play" data-start>Choose your character →</button></section>
 <section class="he-mode-panel" data-online-panel hidden><p>Choose one of four characters. Unclaimed seats are Hard bots.</p><button class="he-main-play he-find-game" data-find>Find game <span>⌕</span></button><button data-create-public class="he-public-create">Play public</button><button class="he-search-cancel" data-cancel hidden>Cancel connection</button><div class="he-room-divider"><span>OR PLAY WITH FRIENDS</span></div><div class="he-room-actions"><button data-create>Create private room</button><input data-code aria-label="Five-character room code" placeholder="CODE" maxlength="5" autocomplete="off" autocapitalize="characters" spellcheck="false"><button data-join>Join</button></div><div class="he-room-ready" hidden><span data-room-kind>PRIVATE TABLE</span><strong data-room-code></strong><p data-room-note>Share this code and the updated game page. Keep the host’s game open.</p><div class="he-room-roster" data-room-roster></div><button data-publish hidden>Open to public matchmaking</button><button class="he-main-play" data-room-play>Choose your character →</button><button data-leave>Leave room</button></div></section>
 <button class="he-main-replay" type="button" data-replay>↺ Replay intro</button><p class="he-main-status" role="status" hidden></p></div>
 <footer class="he-main-footer"><span>♠ CARDS · PLAY CHIPS ONLY</span><span>$2,000 BUY-IN · FOUR SEATS</span></footer>`;
 document.body.appendChild(root);const q=s=>root.querySelector(s),status=q('.he-main-status');let gameType='holdem',level='medium',busy=false;try{level=localStorage.getItem('holdem-difficulty')||'medium'}catch(e){}if(!['easy','medium','hard'].includes(level))level='medium';
 const roomConfig=()=>({...getConfig(),gameType});
 function chooseGame(value){gameType=value==='blackjack'?'blackjack':'holdem';for(const button of root.querySelectorAll('[data-game]'))button.setAttribute('aria-pressed',String(button.dataset.game===gameType));difficulty(level)}
 for(const button of root.querySelectorAll('[data-game]'))button.onclick=()=>{if(window.HoldEmRoom.ready){error('Leave your room to switch games.');return}chooseGame(button.dataset.game)};
 const error=message=>{status.textContent=message;status.hidden=!message};
 function difficulty(value){level=value;for(const b of root.querySelectorAll('[data-level]'))b.setAttribute('aria-pressed',String(b.dataset.level===level));q('[data-level-copy]').textContent={easy:'Relaxed bots make more mistakes and looser calls.',medium:'Balanced play, with occasional bluffs.',hard:'More careful reads, stronger decisions and measured aggression.'}[level];if(gameType==='blackjack')q('[data-level-copy]').textContent={easy:'Casual bots make occasional mistakes. The house rules stay fair.',medium:'Balanced bots use sensible hit and stand decisions.',hard:'Bots use basic strategy. Every seat plays the same house rules.'}[level];try{localStorage.setItem('holdem-difficulty',level)}catch(e){}}
 difficulty(level);for(const b of root.querySelectorAll('[data-level]'))b.onclick=()=>difficulty(b.dataset.level);
 q('[data-single]').onclick=()=>{q('[data-single-panel]').hidden=false;q('[data-online-panel]').hidden=true;error('')};q('[data-online]').onclick=()=>{q('[data-single-panel]').hidden=true;q('[data-online-panel]').hidden=false;error('')};
 q('[data-start]').onclick=()=>{window.HoldEmMatch?.cancel();window.HoldEmMatch?.unpublish();window.HoldEmRoom?.leave();onPlay({mode:'single',difficulty:level,gameType})};
 async function connect(action,label="Connecting to the room service…"){if(busy)return;busy=true;for(const b of root.querySelectorAll('[data-create],[data-create-public],[data-join],[data-find],[data-publish]'))b.disabled=true;root.setAttribute('aria-busy','true');error(label);updateRoom();try{await action();error(window.HoldEmRoom.ready?(window.HoldEmMatch.public?'PUBLIC lobby':'Room '+window.HoldEmRoom.code)+' is ready. Choose your character, then ready up.':'');updateRoom()}catch(e){error(e.message||'Could not connect.')}finally{busy=false;root.setAttribute('aria-busy','false');for(const b of root.querySelectorAll('[data-create],[data-create-public],[data-join],[data-find],[data-publish]'))b.disabled=false;updateRoom()}}
 q('[data-create-public]').onclick=()=>connect(()=>window.HoldEmMatch.find(roomConfig()),'Creating your public room…');q('[data-create]').onclick=()=>connect(()=>{window.HoldEmMatch.cancel();window.HoldEmMatch.unpublish();return window.HoldEmRoom.create(roomConfig())});q('[data-find]').onclick=()=>connect(()=>window.HoldEmMatch.find(roomConfig()));q('[data-cancel]').onclick=()=>{window.HoldEmMatch.cancel();window.HoldEmRoom.leave();error('Search cancelled.')};q('[data-publish]').onclick=()=>window.HoldEmMatch.public?(window.HoldEmMatch.unpublish(),updateRoom()):connect(()=>window.HoldEmMatch.publish());q('[data-join]').onclick=()=>connect(()=>{window.HoldEmMatch.cancel();window.HoldEmMatch.unpublish();return window.HoldEmRoom.join(q('[data-code]').value)});q('[data-code]').oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,'');q('[data-code]').onkeydown=e=>{if(e.key==='Enter')q('[data-join]').click()};
 q('[data-room-play]').onclick=()=>onPlay({mode:'online',difficulty:'hard',gameType:window.HoldEmRoom.gameType});q('[data-leave]').onclick=()=>window.HoldEmRoom.leave();
 function updateRoom(){const room=window.HoldEmRoom,pub=window.HoldEmMatch.public;if(room?.ready)chooseGame(room.gameType);for(const button of root.querySelectorAll('[data-game]'))button.disabled=busy||!!room?.ready;q('.he-room-ready').hidden=!room?.ready;q('[data-room-code]').textContent=pub?'PUBLIC':room?.code||'';q('[data-room-kind]').textContent=(room?.gameType==='blackjack'?'BLACKJACK · ':'HOLD EM · ')+(pub?'PUBLIC ROOM':'PRIVATE ROOM');q('[data-room-note]').textContent=pub?'Choose your character. Once another player joins, both ready up to begin. Empty seats are Hard bots.':'Share this code and the updated game page. Empty seats are Hard bots.';q('[data-publish]').hidden=!room?.ready||!room.isHost;q('[data-publish]').textContent=pub?'Make table invite-only':'Open to public matchmaking';q('[data-find]').hidden=!!room?.ready;q('[data-cancel]').hidden=!busy&&!window.HoldEmMatch.searching;q('[data-create-public]').hidden=!!room?.ready;q('[data-room-roster]').replaceChildren(...['Vince','Bruno','Miles','Gus'].map((name,i)=>{const player=room?.roster[i],el=document.createElement('div');el.className=player?'human':'bot';const title=document.createElement('b'),tag=document.createElement('small');title.textContent=name;tag.textContent=player?(room.availableSeats().includes(i)?'YOU':player.ready?'PLAYER':'CHOOSING'):'HARD BOT';el.append(title,tag);return el}))}
 window.addEventListener('holdem:room',updateRoom);window.addEventListener('holdem:match',updateRoom);window.addEventListener('holdem:match-status',e=>error(e.detail));window.addEventListener('holdem:room-status',e=>error(e.detail));
 q('[data-replay]').onclick=onReplay;q('[data-exit]').onclick=()=>document.getElementById('exitGame')?.click();
 function show(focus=true){root.hidden=false;document.body.classList.add('holdem-main-open');updateRoom();if(focus)requestAnimationFrame(()=>{if(!root.hidden)q('[data-single]').focus({preventScroll:true})})}
 function hide(){root.hidden=true;document.body.classList.remove('holdem-main-open')}
 show(false);return {show,hide,element:root,get isOpen(){return !root.hidden},setError:error};
};
})();
