/* Four character seats. The host owns poker state; only public data leaves a room. */
(function(){
'use strict';
let gameType='holdem',peer=null,connection=null,host=false,code='',self=2,roster={},clients=new Map(),pending=null,operation=null,ready=false,lastSnapshot=null,lastSerial=-1,botLooks={},epoch=0,loader=null;
const change=()=>window.dispatchEvent(new CustomEvent('holdem:room',{detail:{code,ready,host,self,roster:{...roster}}})),status=message=>window.dispatchEvent(new CustomEvent('holdem:room-status',{detail:message}));
function load(){if(window.Peer)return Promise.resolve();if(loader)return loader;loader=new Promise((resolve,reject)=>{const script=document.createElement('script');let settled=false;const timer=setTimeout(()=>finish(Error('The room service took too long to load. Check your connection and try again.')),15000);function finish(error){if(settled)return;settled=true;clearTimeout(timer);script.onload=script.onerror=null;if(error){loader=null;script.remove();reject(error)}else resolve()}script.src='https://unpkg.com/peerjs@1.5.5/dist/peerjs.min.js';script.onload=()=>finish(window.Peer?null:Error('Room service unavailable.'));script.onerror=()=>finish(Error('Room service could not load. Check your internet connection.'));document.head.appendChild(script)});return loader}
function sanitize(config){const seat=Number(config.chosen);if(!Number.isInteger(seat)||seat<0||seat>3)throw Error('Choose one of the four characters.');return{seat,look:HoldEmWardrobe.normalize(config.customizations?.[seat])}}
function privateState(snapshot,seat){return {...snapshot,self:seat,players:snapshot.players.map(p=>({...p,hole:snapshot.gameType==='blackjack'||p.id===seat||snapshot.phase==='complete'&&snapshot.showdown&&!p.folded?p.hole:[],result:snapshot.phase==='complete'&&snapshot.showdown&&!p.folded?p.result:null}))}}
function broadcast(snapshot){if(!host)return;lastSnapshot=snapshot;for(const c of clients.values())if(c.open&&Number.isInteger(c.seat))c.send({type:'state',snapshot:privateState(snapshot,c.seat)})}
function shareRoster(){for(const c of clients.values())if(c.open)c.send({type:'roster',roster,botLooks});change();window.TablePoker?.rosterChanged()}
function leave(){epoch++;if(operation){clearTimeout(operation.timer);operation.reject(Error('Connection cancelled.'));operation=null}if(pending){clearTimeout(pending.timer);pending.reject(Error('Room closed.'));pending=null}for(const c of clients.values()){clearTimeout(c.seatTimer);c.close()}clients.clear();connection?.close();peer?.destroy();peer=null;connection=null;ready=false;host=false;code='';roster={};lastSnapshot=null;lastSerial=-1;change()}
function begin(resolve,reject,message){const op={resolve,reject,timer:setTimeout(()=>{if(operation===op){operation=null;leave();reject(Error(message))}},18000)};operation=op;return op}
function complete(op,error){if(operation!==op)return;clearTimeout(op.timer);operation=null;if(error){leave();op.reject(error)}else op.resolve()}
function roomError(e,myEpoch,op){if(myEpoch!==epoch)return;const error=Error(e.message||'Could not connect to the room.');if(operation===op)complete(op,error);else{ready=false;change();status(error.message)}}
async function create(config){const requestedEpoch=epoch;await load();if(requestedEpoch!==epoch)throw Error("Connection cancelled.");const choice=sanitize(config);leave();gameType=config.gameType==='blackjack'?'blackjack':'holdem';host=true;self=choice.seat;botLooks=HoldEmSeating.botLooks(HoldEmWardrobe);const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',bytes=new Uint8Array(5);crypto.getRandomValues(bytes);code=Array.from(bytes,v=>alphabet[v%alphabet.length]).join('');roster[self]={owner:'host',nickname:window.GameRoomProfile?.name||'Player',look:choice.look,ready:false};const myEpoch=epoch;
 return new Promise((resolve,reject)=>{const op=begin(resolve,reject,'Could not reach the room service.');try{peer=new Peer('cards-haul-v3-'+code,{debug:0})}catch(e){complete(op,e);return}peer.on('open',()=>{if(myEpoch!==epoch)return;try{ready=true;window.TablePoker?.configure({mode:'online',difficulty:'hard',gameType});shareRoster();complete(op)}catch(e){complete(op,Error('Room setup failed: '+e.message))}});peer.on('error',e=>roomError(e,myEpoch,op));peer.on('disconnected',()=>{if(myEpoch!==epoch)return;ready=false;change();status('The room service disconnected. Reconnect from Multiplayer.')});peer.on('connection',c=>{
 if(myEpoch!==epoch){c.close();return}if(clients.size>=3){c.on('open',()=>{c.send({type:'error',message:'This table is full. Search for another game.'});setTimeout(()=>c.close(),150)});return}clients.set(c.peer,c);
 c.on('open',()=>{if(myEpoch!==epoch)return;c.send({type:'roster',roster,botLooks});c.send({type:'welcome',code,version:3,gameType});c.seatTimer=setTimeout(()=>{if(!Number.isInteger(c.seat))c.close()},120000)});
 c.on('data',data=>{if(myEpoch!==epoch||!data||typeof data!=='object')return;
  if(data.type==='claim'){
   const seat=Number(data.seat);if(!Number.isInteger(seat)||seat<0||seat>3||roster[seat]&&roster[seat].owner!==c.peer){c.send({type:'claim-result',ok:false,message:'That character is already taken. Choose another.'});return}
   if(Number.isInteger(c.seat)&&c.seat!==seat&&lastSnapshot&&!['idle','complete'].includes(lastSnapshot.phase)){c.send({type:'claim-result',ok:false,message:'Finish the hand before changing characters.'});return}
   clearTimeout(c.seatTimer);if(Number.isInteger(c.seat))delete roster[c.seat];c.seat=seat;roster[seat]={owner:c.peer,nickname:window.GameRoomProfile?.clean(data.nickname)||'Player',look:HoldEmWardrobe.normalize(data.look),ready:!!data.ready};c.send({type:'claim-result',ok:true,seat});shareRoster();if(lastSnapshot)c.send({type:'state',snapshot:privateState(lastSnapshot,seat)});
  }else if(data.type==='prop'&&Number.isInteger(c.seat)&&data.seat===c.seat)sendProp(c.seat,data.action);
  else if(data.type==='look'&&Number.isInteger(c.seat)&&roster[c.seat]){roster[c.seat].yaw=Math.max(-.85,Math.min(.85,Number(data.yaw)||0));roster[c.seat].pitch=Math.max(-.75,Math.min(.2,Number(data.pitch)||0));for(const other of clients.values())if(other!==c&&other.open)other.send({type:'look',seat:c.seat,yaw:roster[c.seat].yaw,pitch:roster[c.seat].pitch})}
  else if(data.type==='action'&&roster[c.seat]?.ready&&['fold','call','check','raise','wager','hit','stand','double','split'].includes(data.action?.kind)){if(data.serial===lastSnapshot?.serial)window.TablePoker?.hostAction(c.seat,data.action);if(lastSnapshot)c.send({type:'action-result',snapshot:privateState(lastSnapshot,c.seat)})}
 });
 c.on('close',()=>{clearTimeout(c.seatTimer);if(myEpoch!==epoch)return;clients.delete(c.peer);if(Number.isInteger(c.seat))delete roster[c.seat];shareRoster()});c.on('error',()=>c.close());
 })});
}
async function join(value){const entered=String(value).trim().toUpperCase();if(!/^[A-HJ-NP-Z2-9]{5}$/.test(entered))throw Error('Enter a five-character room code.');const requestedEpoch=epoch;await load();if(requestedEpoch!==epoch)throw Error('Connection cancelled.');leave();code=entered;const myEpoch=epoch;
 return new Promise((resolve,reject)=>{const op=begin(resolve,reject,'Room not found. Keep the host’s game open and check the code.');try{peer=new Peer(undefined,{debug:0})}catch(e){complete(op,e);return}peer.on('error',e=>roomError(e,myEpoch,op));peer.on('disconnected',()=>{if(myEpoch!==epoch)return;ready=false;change();status('The room service disconnected. Reconnect from Multiplayer.')});peer.on('open',()=>{if(myEpoch!==epoch)return;connection=peer.connect('cards-haul-v3-'+code,{reliable:true,serialization:'json'});
  connection.on('data',data=>{if(myEpoch!==epoch||!data||typeof data!=='object')return;
   if(data.type==='welcome'){if(data.version!==3){complete(op,Error('This host is using a different Cards build. Both players need the updated version.'));return}try{gameType=data.gameType==='blackjack'?'blackjack':'holdem';ready=true;window.TablePoker?.configure({mode:'online',difficulty:'hard',gameType});change();complete(op)}catch(e){complete(op,Error('Room setup failed: '+e.message))}}
   if(data.type==='roster'){roster=data.roster;botLooks=data.botLooks||{};change()}
   if(data.type==='claim-result'){if(data.ok){self=data.seat;pending?.resolve()}else pending?.reject(Error(data.message));clearTimeout(pending?.timer);pending=null;change()}
   if((data.type==='state'&&data.snapshot.serial>lastSerial)||(data.type==='action-result'&&data.snapshot.serial>=lastSerial)){lastSerial=data.snapshot.serial;window.TablePoker?.receive(data.snapshot)}
   if(data.type==='prop')window.dispatchEvent(new CustomEvent('holdem:prop',{detail:{seat:data.seat,action:data.action||'pickup'}}));
   if(data.type==='look'&&roster[data.seat]){roster[data.seat].yaw=data.yaw;roster[data.seat].pitch=data.pitch;window.dispatchEvent(new Event('holdem:look'))}
   if(data.type==='error'){const error=Error(data.message);if(operation===op)complete(op,error);else status(error.message)}
  });
  connection.on('close',()=>{if(myEpoch!==epoch)return;if(operation===op){complete(op,Error('This table closed while connecting.'));return}ready=false;if(pending){clearTimeout(pending.timer);pending.reject(Error('The host closed the room.'));pending=null}change();status('The host closed the room. Find another game or reconnect.')});connection.on('error',e=>roomError(e,myEpoch,op));
 })});
}
function claim(config,takeSeat=false){let choice;try{choice=sanitize(config)}catch(e){return Promise.reject(e)}const{seat,look}=choice;if(!ready)return Promise.reject(Error('Connect to a room first.'));if(host){if(seat!==self&&lastSnapshot&&!['idle','complete'].includes(lastSnapshot.phase))return Promise.reject(Error('Finish this hand before changing characters.'));if(roster[seat]&&roster[seat].owner!=='host')return Promise.reject(Error('That character is already taken.'));delete roster[self];self=seat;roster[seat]={owner:'host',nickname:window.GameRoomProfile?.name||'Player',look,ready:takeSeat};shareRoster();return Promise.resolve()}return new Promise((resolve,reject)=>{if(pending){clearTimeout(pending.timer);pending.reject(Error('A newer choice replaced this character choice.'))}pending={resolve,reject,timer:setTimeout(()=>{pending=null;reject(Error('The host did not confirm your seat.'))},8000)};connection.send({type:'claim',seat,look,nickname:window.GameRoomProfile?.name||'Player',ready:takeSeat})})}
function sendProp(seat,action='pickup'){if(!['pickup','puff','down'].includes(action))return;window.dispatchEvent(new CustomEvent('holdem:prop',{detail:{seat,action}}));for(const c of clients.values())if(c.open)c.send({type:'prop',seat,action})}
window.HoldEmRoom={load,create,join,claim,leave,broadcast,privateState,animateProp(seat,action='pickup'){if(!ready)return;if(host)sendProp(seat,action);else if(seat===self)connection?.send({type:'prop',seat,action})},look(yaw,pitch){if(!ready||!roster[self])return;if(host){roster[self].yaw=yaw;roster[self].pitch=pitch;for(const c of clients.values())if(c.open)c.send({type:'look',seat:self,yaw,pitch})}else connection?.send({type:'look',yaw,pitch})},action(action){if(ready&&connection?.open)connection.send({type:'action',serial:lastSerial,action})},humanSeats(){return Object.keys(roster).map(Number).filter(i=>roster[i].ready)},availableSeats(){return [0,1,2,3].filter(i=>!roster[i]||roster[i].owner===(host?'host':peer?.id))},get gameType(){return gameType},get snapshot(){return lastSnapshot},get pendingPlayers(){return clients.size},get isHost(){return host},get ready(){return ready},get code(){return code},get roster(){return roster},get botLooks(){return botLooks},get self(){return self}};
window.addEventListener('pagehide',leave);
})();
