/* One authoritative chip ledger feeds the table, controls and online snapshots. */
(function(){
'use strict';
let gameType='holdem',game=new HoldEm.Game(),dealtKey='',revealKey='';
const $=id=>document.getElementById(id),money=n=>'$'+Number(n).toLocaleString('en-US');
let self=2,live=false,mode='single',difficulty='medium',timer=null,raise=40,key='',serial=0,tableId=0,remote=null,awardUntil=0,sessionKey='single',awardTimer=null,remotePending=false;
const decisionDuration=45000;let decisionTimer=null,turnDeadline=0,decisionKey='',clockSnapshot=null,remoteDeadline=0,clockFrame=null;
function state(){return{turnDeadline,serverTime:Date.now(),decisionDuration,serial,session:tableId,dealing:!!window.HoldEmDealer?.busy,dealInfo:window.HoldEmDealer?.info,self,mode,difficulty,gameType,dealerHand:gameType==='blackjack'?game.dealerCards.map((c,i)=>game.phase==='complete'||i===0?c:null):[],hand:game.hand,phase:game.phase,actor:game.actor,dealer:game.dealer,board:game.board,players:game.players.map(p=>({...p,hole:p.hole.slice()})),pot:game.phase==='complete'?0:game.pot(),awardedPot:game.phase==='complete'?game.pot():0,payouts:game.payouts,pots:game.pots,showdown:game.showdown,notice:game.notice,legal:game.legal(),bankroll:gameType==='blackjack'?game.players.reduce((n,p)=>n+p.stack,0)+game.pot():game.bankroll}}
function current(){return remote||state()}
function publish(){if(mode!=='online'||window.HoldEmRoom?.isHost)serial++;if((mode!=='online'||window.HoldEmRoom?.isHost)&&gameType==='blackjack'&&['playing','complete'].includes(game.phase)&&dealtKey!==tableId+'/'+game.hand){dealtKey=tableId+'/'+game.hand;window.HoldEmDealer?.start(game.hand,game.players,game.hand===1,0,dealtKey,-1,'Welcome to Blackjack, friends. Get close to twenty-one. Do not get carried away.')}if((mode!=='online'||window.HoldEmRoom?.isHost)&&gameType==='blackjack'&&game.phase==='complete'&&!window.HoldEmDealer?.busy&&revealKey!==tableId+'/'+game.hand){revealKey=tableId+'/'+game.hand;window.HoldEmDealer?.reveal(game.hand,revealKey,game.dealerCards.length)}ensureDecision();const snapshot=current();clockSnapshot=snapshot;render(snapshot);window.dispatchEvent(new CustomEvent('holdem:state',{detail:snapshot}));if(mode==='online'&&window.HoldEmRoom?.isHost)window.HoldEmRoom.broadcast(snapshot);return snapshot}
function render(s){
 const bj=s.gameType==='blackjack';document.body.classList.toggle('blackjack-table',bj);const wordmark=document.querySelector('.wordmark');if(wordmark&&wordmark.dataset.game!==s.gameType){wordmark.dataset.game=s.gameType;wordmark.innerHTML='<small>CARDS</small>'+(bj?'Blackjack':'Hold Em')+'<span>━━ ♠ ━━</span>'}
 const own=s.players[self],yourTurn=live&&!s.dealing&&s.actor===self&&s.phase!=='complete',done=s.phase==='complete'&&!s.dealing;
 $('handNumber').textContent=s.hand||'—';$('pot').textContent=money(s.pot);$('street').textContent=s.phase.toUpperCase();
 $('notice').textContent=done?(bj?'Round '+s.hand+' · Complete':'Hand '+s.hand+(s.showdown?' · Showdown':' · Complete')):s.notice||'Take your seat.';$('betting').classList.toggle('hidden',!yourTurn||bj);$('result').classList.toggle('hidden',!done);$('waiting').classList.toggle('hidden',yourTurn||done);
 $('waiting').textContent=s.dealing?'The dealer is preparing the table…':s.actor>=0?s.players[s.actor].name+' is thinking…':'Waiting for the next hand.';
 const community=document.querySelector('[data-community]');if(community){const ranks={11:'J',12:'Q',13:'K',14:'A'},suits=['♣','♦','♥','♠'],cards=bj?(s.dealing?(s.dealerHand||[]).slice(0,2).map((c,i)=>i===0?c:null):s.dealerHand||[]):s.board,signature=(bj?'bj':'he')+cards.map(c=>c?.id??'back').join(',');if(community.dataset.cards!==signature){community.dataset.cards=signature;community.replaceChildren(...Array.from({length:bj?Math.max(2,cards.length):5},(_,i)=>{const c=cards[i],el=document.createElement('span');el.className='he-board-card'+(c?(c.s===1||c.s===2?' red':''):' empty');if(c){el.innerHTML='<b>'+ (c.r<11?c.r:ranks[c.r])+'</b><i>'+suits[c.s]+'</i>';el.setAttribute('aria-label',(c.r<11?c.r:ranks[c.r])+' of '+['clubs','diamonds','hearts','spades'][c.s])}else{el.setAttribute('aria-label',bj?'Dealer hidden card':'Undealt card');if(bj){el.classList.add('card-back');el.textContent='♠'}};return el}))}document.querySelector('[data-board-street]').textContent={idle:'COMMUNITY CARDS',preflop:'PRE-FLOP',flop:'THE FLOP',turn:'THE TURN',river:'THE RIVER',complete:s.showdown?'SHOWDOWN':'HAND COMPLETE'}[s.phase]||'COMMUNITY CARDS';if(bj)document.querySelector('[data-board-street]').textContent='DEALER · '+(s.phase==='complete'&&!s.dealing?Blackjack.total(cards.filter(Boolean)).value:cards.length?'SHOWING '+Blackjack.total(cards.filter(Boolean)).value:'AWAITING WAGERS')}
 const roster=document.querySelector('[data-table-players]');if(roster){roster.replaceChildren(...s.players.map(p=>{const el=document.createElement('div');el.className=(p.id===s.actor?'active ':'')+(p.folded?'folded':'');el.textContent=p.name+(p.id===self?' · YOU':mode==='online'?(window.HoldEmRoom.humanSeats().includes(p.id)?' · PLAYER':' · HARD BOT'):' · BOT')+(p.id===s.dealer?' · D':'')+'  '+money(p.stack)+'  '+(p.lastAction||'');return el}))}
 const balance=document.querySelector('[data-table-balance]');if(balance)balance.textContent=own.name+' · '+money(own.stack);
 const pot=document.querySelector('[data-table-pot]');if(pot)pot.textContent=(done?'AWARDED ':'POT ')+money(s.pot||s.awardedPot||0);
 window.HoldEmHud?.update(s);
 const turn=document.querySelector('[data-table-turn]');if(turn)turn.textContent=done?'HAND COMPLETE':yourTurn?'YOUR TURN':s.actor>=0?s.players[s.actor].name.toUpperCase()+'’S TURN':'READY';
 if(yourTurn&&s.legal&&!bj){const l=s.legal,nextKey=s.hand+'|'+s.phase+'|'+own.stack+'|'+l.toCall;if(key!==nextKey){raise=Math.min(l.minRaise,l.maxRaise);key=nextKey}raise=Math.min(l.maxRaise,Math.max(Math.min(l.minRaise,l.maxRaise),raise));$('raiseSlider').min=Math.min(l.minRaise,l.maxRaise);$('raiseSlider').max=l.maxRaise;$('raiseSlider').value=raise;if($('raiseInput')){$('raiseInput').min=Math.min(l.minRaise,l.maxRaise);$('raiseInput').max=l.maxRaise;$('raiseInput').value=raise;$('raiseInput').disabled=!l.canRaise}$('raiseSlider').step=1;$('raiseValue').textContent=money(raise);$('call').textContent=l.check?'Check':'Call '+money(l.call);$('raise').textContent=(raise===l.maxRaise?'All in ':s.players.some(p=>p.bet>0)?'Raise to ':'Bet ')+money(raise);for(const id of ['raiseDown','raiseUp','raiseSlider','raise','minBet','halfPot','potBet','allIn'])$(id).disabled=!l.canRaise}
 renderBlackjack(s,yourTurn);
 if(done){$('resultNote').textContent=s.notice;$('nextHand').textContent=own.stack<(bj?10:1)||!bj&&s.players.filter(p=>p.stack>0).length<2?'New table →':'Next hand →';$('nextHand').disabled=mode==='online'&&!window.HoldEmRoom?.isHost||Date.now()<awardUntil||window.HoldEmTableAnimating}
}

const pokerRules=$('rules').querySelector('ol').parentElement.innerHTML;
 $('rulesButton').addEventListener('click',()=>{const panel=$('rules').querySelector('.rules');if(gameType==='blackjack')panel.innerHTML='<h2>Blackjack</h2><ol><li>Each character plays against the dealer. Start with $2,000 in play chips and wager $10–$500 per round.</li><li>Face cards count as 10. Aces count as 1 or 11. Reach 21 or finish closer than the dealer without busting.</li><li>Hit takes a card. Stand keeps your total. Double adds the same wager, takes one card, and ends that hand.</li><li>Split equal-value pairs once when you can afford the extra wager. Split aces receive one card each. Split 21 is a regular win.</li><li>A natural Blackjack pays 3:2. Regular wins pay 1:1. A push returns your wager. The dealer stands on every 17, including soft 17.</li><li>45 seconds per decision. Timeout places the minimum wager or stands. Online guests control only their own seats.</li></ol><button class="quiet" id="closeRules" data-close-bj-rules>Back to the table</button>';else panel.innerHTML=pokerRules;const close=panel.querySelector('[data-close-bj-rules]')||panel.querySelector('#closeRules');close.onclick=()=>{$('rules').classList.add('hidden');schedule()}});
 const blackjackControls=document.createElement('div');blackjackControls.id='blackjackControls';blackjackControls.hidden=true;blackjackControls.innerHTML='<div class="bj-hand-summary" data-bj-summary></div><div class="bj-wager"><label for="bjWager">YOUR WAGER</label><button type="button" data-bj-minus aria-label="Decrease wager">−</button><input id="bjWager" type="number" inputmode="numeric" min="10" max="500" step="10" value="50"><button type="button" data-bj-plus aria-label="Increase wager">+</button><button type="button" class="action gold" data-bj-action="wager">Place wager</button></div><div class="bj-actions"><button type="button" class="action gold" data-bj-action="hit">Hit</button><button type="button" class="action" data-bj-action="stand">Stand</button><button type="button" class="action" data-bj-action="double">Double</button><button type="button" class="action" data-bj-action="split">Split</button></div><small data-bj-rules>Blackjack pays 3:2 · Dealer stands on soft 17 · One split · Split aces get one card</small>';
$('waiting').before(blackjackControls);
function wager(delta=0){const l=current().legal;if(!l||current().phase!=='betting')return 10;const input=$('bjWager'),n=Number(input.value);input.value=Math.min(l.maxBet,Math.max(l.minBet,Math.round((Number.isFinite(n)?n:50)/10)*10+delta));return Number(input.value)}
blackjackControls.querySelector('[data-bj-minus]').onclick=()=>wager(-10);blackjackControls.querySelector('[data-bj-plus]').onclick=()=>wager(10);$('bjWager').onchange=()=>wager();
for(const button of blackjackControls.querySelectorAll('[data-bj-action]'))button.onclick=()=>act(button.dataset.bjAction,button.dataset.bjAction==='wager'?wager():undefined);
function renderBlackjack(s,yourTurn){const bj=s.gameType==='blackjack';blackjackControls.hidden=!bj;document.querySelector('[data-street-steps]').hidden=bj;const own=s.players[self];if(!bj)return;const betting=s.phase==='betting';blackjackControls.querySelector('.bj-wager').hidden=!betting||!yourTurn;blackjackControls.querySelector('.bj-actions').hidden=betting||!yourTurn;blackjackControls.querySelector('[data-bj-summary]').textContent=betting?'Choose your wager. Each seat plays against the house.':(own.hands||[]).map((h,i)=>(own.hands.length>1?'HAND '+(i+1)+' · ':'')+'TOTAL '+Blackjack.total(h.cards).value+(yourTurn&&i===own.activeHand?' · YOUR MOVE':'')+(h.outcome?' · '+h.outcome:'')).join(' / ');if(betting&&yourTurn){$('bjWager').max=s.legal.maxBet;wager()}for(const button of blackjackControls.querySelectorAll('.bj-actions button'))button.disabled=!s.legal?.[button.dataset.bjAction]||remotePending;document.querySelector('[data-street-next]').textContent=betting?'NEXT UP · THE DEAL':s.phase==='playing'?'NEXT UP · DEALER REVEAL':'ROUND COMPLETE';}

// Only the authority expires a decision. The lightweight HUD tick never broadcasts game state.
function resetDecision(){clearTimeout(decisionTimer);decisionTimer=null;turnDeadline=0;decisionKey=''}
function ensureDecision(){
 if(mode==='online'&&!window.HoldEmRoom?.isHost)return;
 if(!live||window.HoldEmDealer?.busy||!game.legal()){resetDecision();return}
 const nextKey=tableId+'/'+game.hand+'/'+game.phase+'/'+game.actor;
 if(decisionKey===nextKey&&turnDeadline)return;
 resetDecision();decisionKey=nextKey;turnDeadline=Date.now()+decisionDuration;
 const expected=decisionKey;decisionTimer=setTimeout(()=>{if(expected===decisionKey)expireDecision()},decisionDuration);
}
function expireDecision(){
 if(!live||!turnDeadline||Date.now()<turnDeadline||mode==='online'&&!window.HoldEmRoom?.isHost)return false;
 const legal=game.legal();if(!legal)return false;
 const name=game.players[game.actor].name,kind=gameType==='blackjack'?(game.phase==='betting'?'wager':'stand'):legal.check?'check':'fold';
 if(!game.act(kind,legal.minBet))return false;resetDecision();
 game.notice=name+' ran out of time — '+({check:'checked.',fold:'folded.',stand:'stood.',wager:'placed the minimum wager.'}[kind])+(game.phase==='complete'?' '+game.notice:'');
 if(game.phase==='complete')awardUntil=Date.now()+2700;publish();schedule();return true;
}
function tickClock(){
 const s=clockSnapshot,deadline=remote?remoteDeadline:turnDeadline,remaining=deadline?Math.max(0,deadline-Date.now()):0;
 window.HoldEmHud?.clock(s,remaining/1000);
 const el=document.querySelector('[data-decision-clock]');
 if(el){el.hidden=!live||!s||s.dealing||!deadline||s.phase==='complete'||s.phase==='idle';el.querySelector('b').textContent=Math.ceil(remaining/1000)+'s';el.classList.toggle('urgent',remaining<=10000);el.style.setProperty('--remaining',(remaining/decisionDuration*100)+'%')}
}
clockFrame=setInterval(tickClock,200);
function stop(){clearTimeout(timer);timer=null}
function schedule(){stop();ensureDecision();if(!live||window.HoldEmDealer?.busy||(document.hidden&&mode!=='online')||!$('rules').classList.contains('hidden')||game.phase==='complete'||game.actor<0||mode==='online'&&!window.HoldEmRoom?.isHost)return;const humans=mode==='online'?window.HoldEmRoom.humanSeats():[self];if(humans.includes(game.actor))return;timer=setTimeout(()=>{timer=null;if(!live||(document.hidden&&mode!=='online'))return;const action=game.bot();if(action&&game.act(action.kind,action.target))resetDecision();if(game.phase==='complete')awardUntil=Date.now()+2700;publish();schedule()},1150+Math.random()*650)}
function act(kind,target=raise){if(!live||current().dealing)return false;if(mode==='online'&&!window.HoldEmRoom?.isHost){if(remotePending||remote?.actor!==self||!window.HoldEmRoom.ready)return false;remotePending=true;window.HoldEmRoom.action({kind,target});return true}if(expireDecision()||game.actor!==self)return false;const ok=game.act(kind,target);if(ok){resetDecision();if(game.phase==='complete')awardUntil=Date.now()+2700;publish();schedule()}return ok}
function setRaise(value){const s=current(),l=s.legal;if(!l||s.actor!==self)return;raise=Math.round(Math.min(l.maxRaise,Math.max(Math.min(l.minRaise,l.maxRaise),value)));render(s)}
function next(){if(mode==='online'&&!window.HoldEmRoom?.isHost)return;if(window.HoldEmDealer?.busy||Date.now()<awardUntil||window.HoldEmTableAnimating)return;if(game.players[self].stack<(gameType==='blackjack'?10:1)||gameType!=='blackjack'&&game.players.filter(p=>p.stack>0).length<2){game.reset();tableId++;}key='';resetDecision();game.start();if(gameType!=='blackjack')window.HoldEmDealer?.start(game.hand,game.players,game.hand===1,0,tableId+'/'+game.hand,game.dealer);publish();schedule()}
for(const [id,kind]of [['fold','fold'],['call','call'],['raise','raise']])$(id).onclick=()=>act(kind);
$('raiseSlider').oninput=e=>setRaise(Number(e.target.value));$('minBet').onclick=()=>setRaise(current().legal?.minRaise||20);$('halfPot').onclick=()=>{const s=current();setRaise(Math.max(...s.players.map(p=>p.bet))+Math.round((s.pot+(s.legal?.call||0))*.5))};$('potBet').onclick=()=>{const s=current();setRaise(Math.max(...s.players.map(p=>p.bet))+s.pot+(s.legal?.call||0))};$('allIn').onclick=()=>setRaise(current().legal?.maxRaise||0);$('nextHand').onclick=next;
if($('raiseInput'))$('raiseInput').onchange=e=>setRaise(Number(e.target.value));if($('raiseDown'))$('raiseDown').onclick=()=>setRaise(raise-20);if($('raiseUp'))$('raiseUp').onclick=()=>setRaise(raise+20);
const originalClose=$('closeRules').onclick;$('closeRules').onclick=()=>{originalClose?.();schedule()};document.addEventListener('visibilitychange',()=>document.hidden&&mode!=='online'?stop():schedule());window.addEventListener('pagehide',()=>{stop();resetDecision();clearInterval(clockFrame)});
window.TablePoker={
 configure(options={}){const nextMode=options.mode||'single';const nextType=options.gameType==='blackjack'?'blackjack':'holdem';const nextKey=(nextMode==='online'?window.HoldEmRoom.code:'single')+'/'+nextType;if(nextType!==gameType){stop();gameType=nextType;game=new (gameType==='blackjack'?Blackjack.Game:HoldEm.Game)();dealtKey='';live=false}if(nextKey!==sessionKey){resetDecision();game.reset();remote=null;tableId++;sessionKey=nextKey}mode=nextMode;difficulty=mode==='online'?'hard':options.difficulty||'medium';game.options.difficulty=difficulty;if(mode!=='online'||window.HoldEmRoom?.isHost)remote=null},
 start(chosen){self=chosen;live=true;document.body.classList.add('table-live');if(mode==='online'&&!window.HoldEmRoom?.isHost){if(remote)publish();return}if(game.phase==='idle'){game.reset();tableId++;game.start();if(gameType!=='blackjack')window.HoldEmDealer?.start(game.hand,game.players,game.hand===1,0,tableId+'/'+game.hand,game.dealer)}publish();schedule()},
 dealReady(){publish();schedule()},
 pause(){window.HoldEmDealer?.cancel();live=false;stop();resetDecision();tickClock();document.body.classList.remove('table-live')},
 receive(snapshot){remotePending=false;const completed=snapshot.phase==='complete'&&remote?.phase!=='complete';self=snapshot.self;gameType=snapshot.gameType||'holdem';remoteDeadline=snapshot.turnDeadline?Date.now()+Math.max(0,snapshot.turnDeadline-snapshot.serverTime):0;remote={...snapshot};if(completed)awardUntil=Date.now()+2700;publish()},
 hostAction(seat,action){if(!live||window.HoldEmDealer?.busy||expireDecision()||game.actor!==seat)return;const ok=game.act(action.kind,action.target);if(ok){resetDecision();if(game.phase==='complete')awardUntil=Date.now()+2700;publish();schedule()}},
 rosterChanged(){publish();schedule()},get snapshot(){return current()},get self(){return self},get live(){return live},get mode(){return mode},get gameType(){return gameType},act
};
window.addEventListener('holdem:chips-settled',()=>{if(live){clearTimeout(awardTimer);awardTimer=setTimeout(()=>render(current()),Math.max(0,awardUntil-Date.now()))}});
})();
